### ISSUE TITLE
Test case are failing

### ISSUE THREAD

**Issue by pragya-sriharsh** [DevinCodes/rails-replication#1] opened 2023-09-05 06:44 UTC
I just cloned your Github repository and perform these steps:

1. bundle install
2. bundle exec rake db:migrate
3. Run the test cases and they are failed (see failed screenshot) 

**Note: I haven't changed anything in the codebase**

<img width="1727" alt="Screenshot 2023-09-04 at 3 27 35 PM" src="https://github.com/DevinCodes/rails-replication/assets/118921874/5080d3d0-2fff-4ab6-a8e6-b52386479329">

4. When i switched to algolia version from 2.2.2 to 1.19.1(see algolia version screenshot)

<img width="691" alt="Screenshot 2023-09-04 at 3 39 52 PM" src="https://github.com/DevinCodes/rails-replication/assets/118921874/5b642b8f-aa21-4ded-9427-934e80ed92d1">

Test cases are run successfully.(see success screenshot)

<img width="1283" alt="Screenshot 2023-09-04 at 3 27 19 PM" src="https://github.com/DevinCodes/rails-replication/assets/118921874/4a13dca7-f42d-4a69-94e5-65956680d319">

**Comment by DevinCodes** [comment] 2023-09-05 07:01
Hey @pragya-sriharsh !

Interestingly enough I'm not able to replicate this: the tests pass on my machine for both versions you specify here. Could you include the `Gemfile.lock` you have after updating the version please?

**Comment by pragya-sriharsh** [comment] 2023-09-05 07:09
Hey @DevinCodes !

No changes are showing in Gemfile.lock file after running "bundle install" 
<img width="916" alt="Screenshot 2023-09-05 at 12 38 33 PM" src="https://github.com/DevinCodes/rails-replication/assets/118921874/e588f0e6-cf39-446f-896b-751185c350e8">

**Comment by pragya-sriharsh** [comment] 2023-09-05 07:15
Hey @DevinCodes !

It seems i don't have enough access to push my changes. Can you confirm me once ?

**Comment by DevinCodes** [comment] 2023-09-05 07:21
It's okay, I think I've been able to reproduce the issue! It looks like the change in question that introduced this different behaviour comes from https://github.com/algolia/algoliasearch-rails/pull/338

The logic used there to determine if an attribute has changed was revised here. Instead of going with `false` as default for the objectID, it goes with `true`, which I believe is causing the record to be marked as needing to be reindexed. I'll ask around but this looks like an unintended side effect, if this is indeed the case I'll work on a fix for this!

**Comment by pragya-sriharsh** [comment] 2023-09-05 07:25
Okay thanks. Hope will revert back soon.

**Comment by pragya-sriharsh** [comment] 2023-09-08 05:02
@DevinCodes Any update ?

**Comment by DevinCodes** [comment] 2023-09-08 15:38
I've worked on a PR that should fix this issue: https://github.com/algolia/algoliasearch-rails/pull/436

If you have some time and would like to test the changes in the PR out, that would be super helpful! I hope to get the PR out early next week. Cheers!

**Comment by pragya-sriharsh** [comment] 2023-09-11 10:16
@DevinCodes , I tried and test cases are passing now. you saved me! :)

**Comment by pragya-sriharsh** [comment] 2023-09-12 05:03
@DevinCodes , I noticed the your PR has been merged into master branch. When you push these changes in a new tag release or existing tag release? I don't want to reference the master branch because if there are any changes made to the master branch in the future, it could potentially affect this release.

**Comment by DevinCodes** [comment] 2023-09-12 05:46
Yes, I'm doing a release today! I'll leave a message here when it's done 🙂

**Comment by DevinCodes** [comment] 2023-09-12 06:54
@pragya-sriharsh v2.3.0 of the gem is out now, you should be able to use that one to have this latest fix in your project! 🙂

**Closed by DevinCodes** 2023-09-12 06:54 UTC
